### ISSUE TITLE
文档页,搜索错误, 能搜索到,不能打开

### ISSUE THREAD

**Issue by uulaile** [Misuzu2027/syplugin-document-search#1]
文档页,搜索错误, 能搜索到,不能打开。
思源版本v2.12.6
![image](https://github.com/Misuzu2027/syplugin-document-search/assets/96331996/980a1249-4c90-478a-b497-b612c94a4381)
![image](https://github.com/Misuzu2027/syplugin-document-search/assets/96331996/7f8ed15b-953c-44e4-9774-e9d6c35b65de)

**Comment by Misuzu2027** [comment]
可以开启这个设置：
![image](https://github.com/Misuzu2027/syplugin-document-search/assets/154575405/2c5b2fa4-b41c-4569-8815-7fd76a160bb0)
出现这种情况是因为当前文档只有文档块匹配上了，然后没启用这个选项，就把文档块给过滤掉了。

**Comment by Misuzu2027** [comment]
后续优化一下，如果关闭这个选项，然后查询结果只有文档块，就还是显示出来。

**Comment by uulaile** [comment]
哦,原来如此,暗黑模式下,没看到那个按钮🤣
