### ISSUE TITLE
希望增加“新建文档”功能

### ISSUE THREAD

**Issue by Jiangshuon** [Misuzu2027/syplugin-document-search#10]
没搜到时就可以直接新建了。这点官方搜索是有的，希望大佬能加上

![image](https://github.com/Misuzu2027/syplugin-document-search/assets/67137548/74c21bb9-51a4-432c-b607-62784e9497eb)

**Comment by Misuzu2027** [comment]
这个暂时不考虑了，如果是电脑端的话，新建文档还是很方便的。Ctrl + A 全选 内容， Ctrl + C 复制， Ctrl + N 新建文档， Ctrl + V 粘贴标题。全程一只手操作快捷键就可以了。
