### ISSUE TITLE
疑似bug？  当前文档搜索 开关在 v3.1.2 版本里似乎没有了

### ISSUE THREAD

**Issue by Ctipsy** [Misuzu2027/syplugin-document-search#11]
![image](https://github.com/user-attachments/assets/8c5615c4-e0e3-4c2c-8924-2e8ef57b4e3b)

**Comment by Misuzu2027** [comment]
啊，我看了下历史版本，页签搜索一直没有“只当前文档搜索”的开关，只有侧边栏才有

**Comment by Ctipsy** [comment]
我是从这里看到的
![image](https://github.com/user-attachments/assets/413cee2a-fe21-4428-862b-f9ca9ccce6fa)

**Comment by Misuzu2027** [comment]
这个是侧边栏（Dock栏）的搜索 
![image](https://github.com/user-attachments/assets/e1087316-00c8-4007-8f30-c6dafe1e7ee4)
