### ISSUE TITLE
无法搜索文档标题

### ISSUE THREAD

**Issue by Smi1eSEC** [Misuzu2027/syplugin-document-search#12]
无法搜索到顶层每个笔记本的标题

**Comment by Smi1eSEC** [comment]
看了下是有些文档标题可以搜到，有的搜不到

**Comment by Misuzu2027** [comment]
你好，可以描述下使用场景吗？文档标题是可以搜索到的，笔记本因为不是文档，所以搜不到。

**Comment by Smi1eSEC** [comment]
笔记本太多的情况下，想直接通过这个插件侧边栏搜索到指定笔记本

**Comment by Misuzu2027** [comment]
这个确实做不到，目前只会搜索到文档并展示，笔记本不会出现在搜索结果当中。

**Comment by Smi1eSEC** [comment]
思源没有提供接口吗，我看插件不是可以配置在哪些笔记本中搜索

**Comment by Misuzu2027** [comment]
思源插件系统是可以实现在文档树搜索笔记本的。

不过本插件不支持这个功能，本插件目前是搜索符合条件的“文档”，结果列表也只能展示“文档”。因为“文档”和“笔记本“ 它俩的类型和功能都不一样。

**Comment by Misuzu2027** [comment]
Misuzu 插件中加入了这个功能，有需要可以使用这个插件。

**Comment by Smi1eSEC** [comment]
请问Misuzu这个插件怎么用 没看懂

**Comment by Misuzu2027** [comment]
在设置中开启这个，
![image](https://github.com/user-attachments/assets/d228bea7-9f05-4b09-a84b-9c600acc49a5)
然后文档树就会出现一个搜索框，
![image](https://github.com/user-attachments/assets/3a756555-3ffc-4f76-8ef8-84a6f947fe03)
这个搜索框只会根据关键字过滤笔记本
