### ISSUE TITLE
建议增加搜索悬浮框

### ISSUE THREAD

**Issue by 879611427** [Misuzu2027/syplugin-document-search#13]
预期效果：
未搜索前只展示搜索悬浮框
默认搜索当前笔记内容
可选搜索全部笔记内容
搜索时还可以滚动查看当前页面内容
使用场景：第一次搜索完key1,接着又想搜索一次key2，但是要在当前笔记滚动看下内容才知道key2是什么

**Comment by Misuzu2027** [comment]
我个人觉得使用 侧边栏搜索 可以满足这个使用场景。

**Comment by 879611427** [comment]
> 我个人觉得使用 侧边栏搜索 可以满足这个使用场景。

Nice!没注意到还有侧边栏
