### ISSUE TITLE
是否能在siyuan自带的全局搜索悬浮窗中增加按钮

### ISSUE THREAD

**Issue by Chenm4** [Misuzu2027/syplugin-document-search#14]
就是在自带的全局搜索悬浮窗中增加全局按文档搜索的选项，打开这个选项可以搜索出文档内包含某些关键词的文档，这样可能更方便？我不知道有无这种打算。例如在下图中的1处添加选项
![image](https://github.com/user-attachments/assets/9d8d3824-4bd6-485f-9742-246a2c4ead75)

**Comment by Misuzu2027** [comment]
没有这种打算，可以考虑使用 “简易搜索” 插件，该插件支持在官方搜索输入框加参数实现全文搜索。
