### ISSUE TITLE
请问能否增加 方向键 切换搜索结果的功能

### ISSUE THREAD

**Issue by cordinGH** [Misuzu2027/syplugin-document-search#15]
感谢作者，插件非常棒，相较于官方搜索功能而言更清晰易用！
有一点可惜的是，不能像官方搜索那样，搜索之后直接 **`方向键`** 切换搜索结果（如下图）。不知道能否增加这个功能。
![up&down 切换搜索结果](https://github.com/user-attachments/assets/c8f9df8f-d87d-4eeb-8c97-d5b86d8dd35c)

**Comment by Misuzu2027** [comment]
现在是有上下键切换搜索结果的，不过没有切换实时预览，只能回车打开文档。后续改进一下，上下选择后切换预览。

**Comment by Misuzu2027** [comment]
v0.10.8 已更新，如果集市没看见更新，可能需要重启思源。

**Comment by cordinGH** [comment]
> v0.10.8 已更新，如果集市没看见更新，可能需要重启思源。

非常丝滑！五星！！respect！
