### ISSUE TITLE
希望能增加一个tab模式打开的按钮

### ISSUE THREAD

**Issue by anrgct** [Misuzu2027/syplugin-document-search#3]
当前点击高亮选项，文档会以预览打开，希望增加一个正常tab模式打开的按钮

**Comment by Misuzu2027** [comment]
双击会打开 tab ，这里跟官方的操作逻辑一样

**Comment by anrgct** [comment]
你好，我本地双击搜索结果的标题项，不会打开tab文档，会折叠-展开，如果双击块的结果项，预览会闪动两次

**Comment by Misuzu2027** [comment]
标题项确实无法双击打开，块是支持 双击 或 选中后回车 打开 tab 的，我刚刚试了下集市最新版的插件，是可以的。下面是录屏：

https://github.com/Misuzu2027/syplugin-document-search/assets/154575405/9a0e9ff9-6ba2-4c44-bd49-71c2b2e16a52

**Comment by anrgct** [comment]
我装了最新思源笔记和插件，但我的是Mac环境的，我试了下大部分双击都不会打开tab，偶尔会触发一下。

**Comment by Misuzu2027** [comment]
我明白了， 估计是 双击响应的时间 设置的较短造成的，刚刚更新了 v0.6.2 版本，可以在其他设置中修改双击响应的时间阈值，如图所示：
![image](https://github.com/Misuzu2027/syplugin-document-search/assets/154575405/e9df55d5-ff88-444c-a588-8d2eb3dabe4e)
你的这种情况时需要把数字调大点，可以尝试300、400。
不过数字越大，单击预览区后响应延迟也会变长，可以根据自身需求调整。

**Comment by anrgct** [comment]
可以了，阈值我改成250就挺合适的，谢谢！建议如果默认值改成250会不会比较好？”双击可以打开tab、可以自定义设置阈值“应该在说明里补充，不然用户不知道

**Comment by Misuzu2027** [comment]
不同设备之间可能会有差异，之前是看到官方这里设置的也是190😂，或许插件和原生之间的响应也有细微差别。
暂时不改成250了，后续会完善说明文档，依据设备环境自己设置确实更能满足需求。

**Comment by anrgct** [comment]
好的，感谢👍
