### ISSUE TITLE
有无关联快捷键的设置

### ISSUE THREAD

**Issue by pakeh2866** [Misuzu2027/syplugin-document-search#4]
RT

**Comment by Misuzu2027** [comment]
目前有三个操作支持快捷键：打开文档搜索页签、文档搜索 Dock、扁平化文档树 Dock 。均可在 设置 -> 快捷键 中找到并修改：
![微信图片_20240416093531](https://github.com/Misuzu2027/syplugin-document-search/assets/154575405/a641543a-0bfc-43f5-81ce-bb7b49acd188)

**Comment by pakeh2866** [comment]
感谢
