### ISSUE TITLE
如图，alt + e 扁平化文档搜索，有时候会出现卡转圈的情况，而且这时候搜索框也点不了

### ISSUE THREAD

**Issue by ningchenyu** [Misuzu2027/syplugin-document-search#5]
![image](https://github.com/Misuzu2027/syplugin-document-search/assets/42766474/e6b49b7c-89c9-43bd-aaa3-7b04ac5a38b1)

**Comment by Misuzu2027** [comment]
麻烦下次出现的时候，右下角点击 帮助 -> 开发者工具 ，看看 控制台 有没有报错信息

**Comment by Misuzu2027** [comment]
刚刚优化了一下这个 转圈 蒙版的位置，如果出现异常导致 转圈 不会取消，可以通过修改搜索框的查询条件，使其重新刷新，防止 Dock 栏直接卡死用不了了。
