### ISSUE TITLE
alt+Q 的时候，可以刷新搜索框的内容吗（或者框起来）

### ISSUE THREAD

**Issue by pakeh2866** [Misuzu2027/syplugin-document-search#6]
![image](https://github.com/Misuzu2027/syplugin-document-search/assets/5708881/f19d6a7a-3458-4ef2-94c8-be5e75db34fc)

目前按alt+Q，是直接出现上一次的结果。

如果想搜索新的内容，必须按好几次退格，才能把上一次的结果删掉。

**Comment by Misuzu2027** [comment]
可以 ctrl + a 全选后再输入，会方便一点。
重新打开清空就不支持了，因为有些情况可能需要查看上一次搜索历史；
重新打开默认选中全部文字可以加上，试了下官方的搜索页签是这个逻辑。

**Comment by pakeh2866** [comment]
重新打开默认选中全部文字可以加上，试了下官方的搜索页签是这个逻辑。
__________________
能加上这个就很好啦，谢谢大佬。

**Comment by Misuzu2027** [comment]
v0.9.5 加上了，可以到集市更新试试。
