### ISSUE TITLE
用dock搜完之后关闭（使用的是快捷键），高亮仍然存在

### ISSUE THREAD

**Issue by Jiangshuon** [Misuzu2027/syplugin-document-search#9]
用dock搜完之后关闭（使用的是快捷键），高亮仍然存在，是bug吗

![image](https://github.com/Misuzu2027/syplugin-document-search/assets/67137548/d408123e-9ed4-4868-89f5-defaa48d7e3e)

**Comment by Misuzu2027** [comment]
目前清除高亮的方式，只有点击搜索栏中的 X 

![image](https://github.com/Misuzu2027/syplugin-document-search/assets/154575405/17ed25b0-832e-4099-96d0-a8dc01e024ed)

后续可以添加隐藏 dock 后也清除高亮。

**Comment by Jiangshuon** [comment]
好的，多谢大佬
